# Generated by Django 4.0.1 on 2022-01-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_profile_created_profile_updated_profile_type_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_Type',
        ),
    ]
