# Generated by Django 4.0.1 on 2022-01-30 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_bank_name_property_property_type_unit_unit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_name',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='property_type',
            name='type',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='type_profile',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='unit_type',
            name='type',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Unit_Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField()),
                ('date_notice', models.DateTimeField()),
                ('date_out', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.profile')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.unit')),
            ],
        ),
    ]
