# Generated by Django 4.0.1 on 2022-01-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_bank_name_name_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_occupancy',
            name='date_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unit_occupancy',
            name='date_notice',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit_occupancy',
            name='date_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
