# Generated by Django 4.0.1 on 2022-01-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_unit_occupancy_date_in_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type_Profile',
            new_name='Profile_Type',
        ),
    ]
